spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://swarajritik_db_user:m9rbwAbkCCr1kNuh@cluster0.4ykba4o.mongodb.net/code-arena?retryWrites=true&w=majority}

logging:
  level:
    com.codearena: DEBUG
    org.springframework.data.mongodb: DEBUG
